# Generated by Django 3.0.14 on 2024-01-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='image_url',
            field=models.TextField(null=True),
        ),
    ]
