# Generated by Django 3.0.14 on 2024-01-24 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20240124_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='starting_price',
            new_name='price',
        ),
    ]
