# Generated by Django 3.0.14 on 2024-01-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
