# Generated by Django 3.0.14 on 2024-01-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20240127_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
